[package]
name = "onekey_account"
version = "0.1.0"
cairo-version = "2.15.0"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "all"

[dependencies]
starknet = "2.15.0"

[cairo]
sierra-replace-ids = true

[tool.fmt]
max-line-length = 120
sort-module-level-items = true
